server:
  port: 8001

spring:
  application:
    name: currency-exchange-rates

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka